name: Trigger LanguageWire project

on:
  workflow_dispatch:
    inputs:
      option1:
        description: 'Application Name'
        required: true
        type: choice
        options:
          - ports-asset-fleet
          - ports-dashboard
          - ports-subscription
          - ports-preventive-maintenance
      option2:
        description: 'Task'
        required: true
        type: choice
        options:
          - Upload file
          - Download files
      inputString:
        description: 'Enter project ID'
        required: true
        type: string

jobs:
  run-node-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' # Specify the Node.js version

      - name: Install dependencies
        run: npm install

      - name: Run Node.js script
        env:
          OPTION1: ${{ github.event.inputs.option1 }}
          OPTION2: ${{ github.event.inputs.option2 }}
          FIRST_KEY: ${{ vars.KEY }}
          OPTION4: 'token'
          INPUT_STRING: ${{ github.event.inputs.inputString }}
          
        run: node test.js
